version: '3.8'

services: 
  surf-app:
    container_name: surf-app
    image: 2467100/surf-ssr:latest
    environment:
      PORT: "4040"
      MONGO_DB_URI: mongodb://vit:secret@mongo_db:27017/surf
    networks:
      - surf_net
    ports:
      - "4040:4040"
    depends_on:
      - mongo_db
  
  mongo_db:
    image: 2467100/recipe-surf-db:latest
    container_name: mongo_db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: vit
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: surf
    networks:
      - surf_net
    ports:
      - "27017:27017"
     
networks:
  surf_net: