FROM node:12 AS surf-ssr
WORKDIR /usr/src/surf-api
COPY ./dist .
RUN yarn config set unsafe-perm true && yarn
EXPOSE 4040
# RUN npm install -g @angular/cli --unsafe-perm && ng config -g cli.packageManager yarn
CMD ["node", "surfer-app-server/main.js"]